### ISSUE TITLE
Cannot read properties of undefined (reading 'sys') in Nuxt 3

### ISSUE THREAD

**Issue by IVoyt** [wobsoriano/vuetify-sonner#1]
After npm install the package I've inserted <VSonner /> into app.vue but there is error appear after page load

Cannot read properties of undefined (reading 'sys')

What am I doing wrong? Or there are some special instructions of installation in Nuxt 3?

**Comment by wobsoriano** [comment]
Would you be able to make a basic repro?

**Comment by wobsoriano** [comment]
Please update to latest and check Nuxt usage [here](https://github.com/wobsoriano/vuetify-sonner#nuxt)
