### ISSUE TITLE
message queue

### ISSUE THREAD

**Issue by TeslaLyon** [wobsoriano/vuetify-sonner#10]
Can this plug-in display only one message at a time, one after another, for example, set one message every 3 seconds, if there are 3 messages in the queue, wait 3 seconds before displaying the second message, and so on.

**Comment by wobsoriano** [comment]
There's no built-in way to do this, but you can take advantage of the `onDismiss` callback and trigger a new toast:

```vue
<script setup>
toast('First', {
  onDismiss() {
    toast('Second', {
      onDismiss() {
        toast('Third')
      }
    })
  },
})
</script>

<template>
  <VSonner :duration="3000" />
</template>
```
