### ISSUE TITLE
/Users/wobsoriano/tmp/vuetify-sonner/src/Toast.vue could not be resolved... 

### ISSUE THREAD

**Issue by SaiCode-DEV** [wobsoriano/vuetify-sonner#16]
[webview] X [ERROR] Could not resolve "/Users/wobsoriano/tmp/vuetify-sonner/src/Toast.vue?vue&type=style&index=0&scoped=a2d3075d&lang.scss"
[webview]
[webview]     node_modules/vuetify-sonner/dist/index.mjs:63:7:
[webview]       63 │ import "/Users/wobsoriano/tmp/vuetify-sonner/src/Toast.vue?vue&typ...
[webview]          ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[webview]

**Comment by SaiCode-DEV** [comment]
The latest version is still a bit broken...

**Comment by wobsoriano** [comment]
@SaiCode-DEV are you using vite? I have tried it in a fresh vite + vuetify app and didnt get any issues 🫣

**Comment by SaiCode-DEV** [comment]
Yes.... newest version in a new Vue and Vuetify app tested. 
yarn add vuetify-sonner@0.3.2 works fine. no issues whatsoever
