### ISSUE TITLE
[Feature Request] Support toast templates

### ISSUE THREAD

**Issue by douglasg14b** [wobsoriano/vuetify-sonner#23]
`toast.custom` has support for this, it would be nice if this lib exposed this behavior vs wrapping/hiding it.

Thanks!

**Comment by douglasg14b** [comment]
My bad, it looks like this is exposed in `toastOriginal`

**Comment by wobsoriano** [comment]
Not documented, but you can still access the original toast via `toast.toastOriginal` :)

So `toast.toastCustom.custom`

**Comment by douglasg14b** [comment]
Thanks!
