### ISSUE TITLE
dismiss(id) BUG

### ISSUE THREAD

**Issue by zk118** [wobsoriano/vuetify-sonner#28]
### Describe the bug

Hey, there seems to be a bug with the dismiss(toastId) method, I always get this error:
<img width="821" alt="toast" src="https://github.com/wobsoriano/vuetify-sonner/assets/28702453/2a6e2504-bf85-482b-900b-6e1d8d94de79">

### Reproduction

const toastId = toast('Success!');
toast.dismiss(toastId);

### System Info

```bash
-
```

### Severity

blocking all usage of vuetify-sonner

**Comment by wobsoriano** [comment]
Can you update to latest version and see if it fixes this?

**Comment by davidramosweb** [comment]
Hi, there is an [issue with the vue-sonner](https://github.com/xiaoluoboding/vue-sonner/issues/63) library. I have created a [Pull Request](https://github.com/xiaoluoboding/vue-sonner/pull/76) with a solution, and it is awaiting review. Once a new version of the library is released, @wobsoriano will need to update it
