### ISSUE TITLE
[Typings]: Broken Options type

### ISSUE THREAD

**Issue by lukasz-fi** [wobsoriano/vuetify-sonner#29]
### Describe the bug

Using `action` throws a TypeScript type error about missing properties: `id, duration, onAutoClose, onDismiss, important` 
It looks like `ExternalToast` type is imported from an invalid location: `import type { ExternalToast } from 'vue-sonner/lib/types';`

### Reproduction

```typescript
        toast('test', {
          action: {
            label: 'test',
            onClick: () => {
              alert('test');
            },
          },
        });
```

### Logs

```bash
error TS2345: Argument of type '{ action: { label: string; onClick: () => void; }; }' is not assignable to parameter of type 'Options'.
  Type '{ action: { label: string; onClick: () => void; }; }' is missing the following properties from type 'Pick<ExternalToast, "id" | "duration" | "onAutoClose" | "onDismiss" | "important">': id, duration, onAutoClose, onDismiss, important
```

### System Info

```bash
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.13 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.3.0 - ~/.nvm/versions/node/v21.3.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.3.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.122
    Safari: 17.4.1
  npmPackages:
    vue: 3.4.15 => 3.4.15 
    vuetify: 3.5.15 => 3.5.15
```

### Severity

blocking all usage of vuetify-sonner

**Comment by fysiofresh-loki** [comment]
I just started looking at this, and I am seeing the same issue with vue & vuetify3, using typescript.
it works if I don't provide options, but that would severely limit the usefulness of this package.

**Comment by jturbide** [comment]
I am facing the same situation at the moment, for now you can force the vue-sonner version to 1.0.4 and it will work as expected.

```
yarn add vue-sonner@1.0.4
```

in your package.json
```
"vue-sonner": "1.0.4",
"vuetify-sonner": "^0.3.14",
````

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/vuetify-sonner/commit/d92b462c6d67c16ce9140afe849cd3d9b3ebc368

Looks like latest version of `vue-sonner` stopped exporting `ExternalToast` from `/lib/types`. I have to open a PR re-exporting that again on their side 👍🏼
